# Generated by Django 3.1.2 on 2020-10-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubike',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('sbi', models.IntegerField()),
                ('sna', models.TextField()),
                ('snaen', models.TextField()),
                ('bemp', models.IntegerField()),
                ('act', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ubike',
            },
        ),
    ]
