# Generated by Django 2.0.4 on 2018-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('sbi', models.IntegerField()),
                ('sna', models.TextField()),
                ('snaen', models.TextField()),
                ('bemp', models.IntegerField()),
                ('act', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ubike',
            },
        ),
    ]
