# Generated by Django 2.0.4 on 2018-08-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubikeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Ubike',
        ),
    ]
